# documentation at https://docs.travis-ci.com/user/languages/r

language: r
sudo: required
cache: packages  
bioc_required: true
warnings_are_errors: false

# testing btergm is truly a nightmare. the following is an attempt to fix
# https://travis-ci.org/tidymodels/broom/builds/568934841#L8845 pull from
# https://github.com/travis-ci/travis-ci/issues/6987#issuecomment-266754776

services:
  - xvfb

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

matrix:
  include:
  - r: devel
  - r: release
  - r: oldrel
  - r: 3.3
  - r: 3.2

env:
  global:
    - R_MAX_NUM_DLLS=999
    - _R_CHECK_FORCE_SUGGESTS_=true
    - _R_CHECK_CRAN_INCOMING_=true

r_build_args: "--no-build-vignettes"
r_check_args: "--no-build-vignettes --as-cran"
    
matrix:
  allow_failures:
    - r: 3.2
    - r: 3.3

r_binary_packages:
  - psych
  - survival
  - mclust
  - git2r
  - data.table
  - RSiena
  - geometry
  - kernlab
  - FNN
  - maps
  
r_packages:
  - rlang
  - bindrcpp
  - purrr
  - tidyr
  - dplyr
  - readr

r_github_packages:
  - jimhester/lintr
  - tidyverse/tidytemplate

after_success:
  - Rscript -e 'covr::codecov()'
